### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by tasmeeruddinkhan** [AqibChattha/Getaway-Bhabhi-Card-Game#2]
title

**Comment by AqibChattha** [comment]
Hello,

1- Just clone or download the project first.
2- Then open an IDE like eclipse for example.
3- The click open projects from file system
![image](https://github.com/AqibChattha/Getaway-Card-Game/assets/81791938/d5d00240-e7e8-4c3c-ac42-dd90193f81f8)

4- Then add the file path and click finish
![image](https://github.com/AqibChattha/Getaway-Card-Game/assets/81791938/b15865d2-e6dd-481a-879c-755a07e65500)

5- Open the driver file
![image](https://github.com/AqibChattha/Getaway-Card-Game/assets/81791938/1b89d066-5919-49be-bc5b-9d7601687999)

6- Then click run button
![image](https://github.com/AqibChattha/Getaway-Card-Game/assets/81791938/ae70250b-0754-4a2b-bf5f-ab097e780f1b)

I hope this helps.
